### ISSUE TITLE
sendForm method not working in VertX WebClient using Kotlin Coroutine verticle

### ISSUE THREAD

**Issue by JessengBijleng** [vert-x3/vertx-lang-kotlin#138] opened 2019-04-19 13:43 UTC
Hi, 

I've encountered problems using a Kotlin Coroutine verticle. I want to make a simple post request using the VertX Webclient like so:

```
client.post(9443, "myurl", "/myendpoint").followRedirects(true).sendForm(form) {
   logger.debug(it.cause().toString())
}
```

The logger however is never reached, it looks like it's a specific problem for the CoroutineVerticle, when my Verticle extendes a AbstractVerticle i get results as expected. The following exception is thrown:

```
java.lang.NullPointerException
	at nl.ing.api.shepherd.verticle.BrokenClientVerticle$getAuth$1.handle(BrokenClientVerticle.kt:39)
	at nl.ing.api.shepherd.verticle.BrokenClientVerticle$getAuth$1.handle(BrokenClientVerticle.kt:18)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:285)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:272)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:250)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:247)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:257)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:218)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:341)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

Using other send methods (like the default .send) also work as expected, it seems to be only the .sendform that's not working, using .sendForAwait makes the method wait infinitely, nothing is ever returned. 

VertX Core, WebClient, Coroutine, version: 3.7.0
Kotlin Coroutine version: 1.2.0

**Comment by JessengBijleng** [comment] 2019-04-19 16:59
I recreated the issue on a different machine, trying a totally different URL. I get the same results, so atleast it doesn't seem to be a local machine issue. Here is the full stack trace:

`apr. 19, 2019 6:56:40 P.M. io.vertx.core.impl.DeploymentManager
SEVERE: io.vertx.core.streams.ReadStream.pipeTo(Lio/vertx/core/streams/WriteStream;Lio/vertx/core/Handler;)V
java.lang.NoSuchMethodError: io.vertx.core.streams.ReadStream.pipeTo(Lio/vertx/core/streams/WriteStream;Lio/vertx/core/Handler;)V
	at io.vertx.ext.web.client.impl.HttpContext.handleSendRequest(HttpContext.java:439)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:266)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:250)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:247)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:257)
	at io.vertx.ext.web.client.impl.HttpContext.sendRequest(HttpContext.java:173)
	at io.vertx.ext.web.client.impl.HttpContext.handlePrepareRequest(HttpContext.java:330)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:263)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:250)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:247)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:257)
	at io.vertx.ext.web.client.impl.HttpContext.prepareRequest(HttpContext.java:160)
	at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:263)
	at io.vertx.ext.web.client.impl.HttpRequestImpl.sendForm(HttpRequestImpl.java:253)
	at PostVerticle.getAuth(Main.kt:31)
	at PostVerticle.start(Main.kt:22)
	at io.vertx.kotlin.coroutines.CoroutineVerticle$start$1.invokeSuspend(CoroutineVerticle.kt:53)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:234)
	at io.vertx.kotlin.coroutines.VertxCoroutineExecutor.execute(VertxCoroutine.kt:230)
	at kotlinx.coroutines.ExecutorCoroutineDispatcherBase.dispatch(Executors.kt:64)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:409)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at io.vertx.kotlin.coroutines.CoroutineVerticle.start(CoroutineVerticle.kt:51)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:494)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)`

**Comment by Jofairden** [comment] 2019-04-29 07:32
@gmariotti you tagged it as a bug, is this bug relatively easy to fix? I also have this issue and it's a combination of using web and a CoroutineVerticle.

**Comment by Jofairden** [comment] 2019-04-29 13:26
I'm actually getting this issue currently in an AbstractVerticle as well
I narrowed it down to HttpContext, when it is trying to pipe the body stream:
```
                stream.pipeTo(req, (ar) -> {
                    if (ar.failed()) {
                        responseFuture.tryFail(ar.cause());
                        req.reset();
                    }

                });
```
It will complain with:
```
java.lang.NoSuchMethodError: io.vertx.core.streams.ReadStream.pipeTo(Lio/vertx/core/streams/WriteStream;Lio/vertx/core/Handler;)V
```
Which is part of Vertx.Core.
When we look at the pipeTo method, we find a couple of definitions:
```
    void pipeTo(WriteStream<T> var1);

    void pipeTo(WriteStream<T> var1, Handler<AsyncResult<Void>> var2);
```
We are using the one with a handler for AsyncResult, but then why does it complain it cannot find the method? It should work because the request being piped is a WriteStream

It will transform the MultiMap into a io.vertx.ext.web.client.impl.MultipartFormUpload beforehand, is this correct behavior? Because this class has no implementation for the pipeTo methods.

**Comment by gmariotti** [comment] 2019-05-05 06:21
Sorry @JessengBijleng, I didn't have enough time to check this bug. Did you look into @Jofairden latest post? If it's not a libraries version problem, can you create share a reproducer of it?

**Comment by Jofairden** [comment] 2019-05-05 08:34
Upgrading my version fixed it for AbstractVerticle but not for CoroutineVerticle. Maybe something was forgotten in the update for CoroutineVerticles?

**Comment by JessengBijleng** [comment] 2019-05-13 11:26
Hi @gmariotti, i don't feel like its an libraries version problem. So I just created a reproducer repository here: https://github.com/JessengBijleng/vertx-webclient-bug

**Comment by gmariotti** [comment] 2019-05-16 19:09
Hi @JessengBijleng, I just tried your project and it worked fine. I only had to change the status code check from 200 to 301 otherwise it would not print anything

**Comment by JessengBijleng** [comment] 2019-05-21 08:20
Hi @gmariotti, i'm sure I haven't created a good reproducer, didn't have enough time to look at it yet, I see this reproducer also uses different versions than the versions we used when the original problems occurred, my bad. I'll look into this later.

**Comment by tsegismont** [comment] 2022-12-08 17:13
Closing as outdated

**Closed by tsegismont** 2022-12-08 17:13 UTC
Labels: bug, invalid
